TABLE_NAME = 'cn_notes'

COLUMN_NOTE_ID = 'cn_note_id'
COLUMN_NOTE_TITLE = 'cn_note_title'
COLUMN_NOTE_CONTENT = 'cn_note_content'

CREATE_NOTES_TABLE = f"CREATE TABLE IF NOT EXISTS {TABLE_NAME} ({COLUMN_NOTE_ID} INTEGER PRIMARY KEY" \
                     f" AUTOINCREMENT NULL, {COLUMN_NOTE_TITLE} NVARCHAR(30), {COLUMN_NOTE_CONTENT} TEXT NOT NULL);"
